# -*- coding: utf-8 -*-
"""struct-to-dict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/142gV-szoUL3gTtZKpxw48WbrBeilDuVm
"""

student = {
    "name": "Rahul",
    "roll": 101,
    "marks": 87.5
}

print(f"Name: {student['name']}")
print(f"Roll: {student['roll']}")
print(f"Marks: {student['marks']:.1f}")